#!/usr/bin/env bash
# Dual-machine helper. Fedora: do not run this — keep using flutter run as before.
# Mac (first time / missing local.properties): bash tool/bootstrap.sh
#
# Never commits SDK paths. Existing valid android/local.properties is left alone
# (so a Fedora machine is not rewritten).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

os="$(uname -s)"

escape_prop() {
  printf '%s' "$1" | sed 's/\\/\\\\/g'
}

prop_value() {
  local key="$1" file="$2"
  [ -f "$file" ] || return 1
  awk -F= -v k="$key" '$1==k {sub(/^[^=]*=/, ""); print; exit}' "$file"
}

resolve_flutter_sdk() {
  local bin dir sdk
  if command -v flutter >/dev/null 2>&1; then
    bin="$(command -v flutter)"
    while [ -L "$bin" ]; do
      dir="$(cd "$(dirname "$bin")" && pwd)"
      bin="$(readlink "$bin")"
      case "$bin" in
        /*) ;;
        *) bin="$dir/$bin" ;;
      esac
    done
    sdk="$(cd "$(dirname "$bin")/.." && pwd)"
    if [ -x "$sdk/bin/flutter" ]; then
      printf '%s' "$sdk"
      return 0
    fi
  fi
  for sdk in \
    "${FLUTTER_ROOT:-}" \
    "$HOME/Projects/flutter" \
    "$HOME/flutter" \
    /opt/homebrew/share/flutter \
    /opt/homebrew/Caskroom/flutter/latest/flutter
  do
    [ -n "$sdk" ] || continue
    if [ -x "$sdk/bin/flutter" ]; then
      printf '%s' "$sdk"
      return 0
    fi
  done
  return 1
}

resolve_android_sdk() {
  local d
  for d in \
    "${ANDROID_HOME:-}" \
    "${ANDROID_SDK_ROOT:-}"
  do
    [ -n "$d" ] || continue
    if [ -d "$d" ]; then
      printf '%s' "$d"
      return 0
    fi
  done
  if [ "$os" = Darwin ]; then
    d="$HOME/Library/Android/sdk"
  else
    d="$HOME/Android/Sdk"
  fi
  if [ -d "$d" ]; then
    printf '%s' "$d"
    return 0
  fi
  return 1
}

echo "== ScanMe bootstrap ($os) =="

props="$ROOT/android/local.properties"
existing_flutter="$(prop_value flutter.sdk "$props" || true)"
if [ -n "$existing_flutter" ] && [ -x "$existing_flutter/bin/flutter" ]; then
  echo "Keeping existing $props"
  echo "  flutter.sdk=$existing_flutter"
  export PATH="$existing_flutter/bin:$PATH"
  echo "If this machine already ran the app, you can stop here and use: flutter run"
  if [ "$os" != Darwin ]; then
    echo "Linux: not rewriting paths, not running pod install."
    flutter --version | head -n 3
    exit 0
  fi
  flutter_sdk="$existing_flutter"
else
  if ! flutter_sdk="$(resolve_flutter_sdk)"; then
    echo "Flutter SDK not found."
    echo "  Install Flutter and put bin/ on PATH, or clone it to \$HOME/Projects/flutter"
    echo "  https://docs.flutter.dev/get-started/install"
    exit 1
  fi
  export PATH="$flutter_sdk/bin:$PATH"
  echo "Flutter SDK: $flutter_sdk"
  flutter --version | head -n 3

  if android_sdk="$(resolve_android_sdk)"; then
    echo "Android SDK: $android_sdk"
  else
    echo "Android SDK not found (optional until you run Android)."
    echo "  Mac default:    \$HOME/Library/Android/sdk"
    echo "  Fedora default: \$HOME/Android/Sdk"
    android_sdk=""
  fi

  {
    echo "# Generated by tool/bootstrap.sh — gitignored, machine-local. Do not commit."
    if [ -n "$android_sdk" ]; then
      echo "sdk.dir=$(escape_prop "$android_sdk")"
    fi
    echo "flutter.sdk=$(escape_prop "$flutter_sdk")"
  } >"$props"
  echo "Wrote $props"
fi

echo
if command -v java >/dev/null 2>&1; then
  echo "Java:"
  java -version 2>&1 | head -n 3
else
  echo "WARN: no java on PATH."
  echo "  Mac:    brew install --cask temurin@17"
  echo "  Fedora: leave your existing JDK — do not change it for this repo."
fi

echo
echo "flutter pub get..."
flutter pub get

if [ "$os" = Darwin ]; then
  if [ ! -f "$ROOT/ios/Flutter/Generated.xcconfig" ]; then
    echo "WARN: ios/Flutter/Generated.xcconfig missing after pub get; skip pod install."
  elif ! command -v pod >/dev/null 2>&1; then
    echo "WARN: CocoaPods not on PATH. Install: brew install cocoapods  then: (cd ios && pod install)"
  else
    echo "pod install (macOS only)..."
    (cd "$ROOT/ios" && pod install)
  fi
else
  echo "Skipping pod install (iOS is macOS + Xcode only)."
fi

echo
echo "Done. Next: flutter run"
